export const data = [
  {
    employmentId: "1001",
    name: "Alice Johnson",
    startDate: "2023-01-15",
    employmentType: "Full Time",
    role: "IT & Security",
    gender: "Female",
  },
  {
    employmentId: "1002",
    name: "Bob Smith",
    startDate: "2022-12-01",
    employmentType: "Internship",
    role: "Human Resources",
    gender: "Male",
  },
  {
    employmentId: "1003",
    name: "Cathy Brown",
    startDate: "2023-03-21",
    employmentType: "Part Time",
    role: "Administration",
    gender: "Female",
  },
  {
    employmentId: "1004",
    name: "David Wilson",
    startDate: "2021-11-05",
    employmentType: "Full Time",
    role: "Marketing",
    gender: "Male",
  },
  {
    employmentId: "1005",
    name: "Eva Davis",
    startDate: "2020-07-19",
    employmentType: "Contract",
    role: "Finance",
    gender: "Female",
  },
  {
    employmentId: "1006",
    name: "Frank White",
    startDate: "2022-09-14",
    employmentType: "Internship",
    role: "Operations",
    gender: "Male",
  },
  {
    employmentId: "1007",
    name: "Grace Hall",
    startDate: "2023-02-11",
    employmentType: "Part Time",
    role: "Administration",
    gender: "Female",
  },
  {
    employmentId: "1008",
    name: "Henry Lee",
    startDate: "2022-06-27",
    employmentType: "Full Time",
    role: "Sales",
    gender: "Male",
  },
  {
    employmentId: "1009",
    name: "Ivy King",
    startDate: "2023-08-02",
    employmentType: "Contract",
    role: "Human Resources",
    gender: "Female",
  },
  {
    employmentId: "1010",
    name: "Jack Green",
    startDate: "2023-04-18",
    employmentType: "Full Time",
    role: "IT & Security",
    gender: "Female",
  },
  {
    employmentId: "1011",
    name: "Kelly Wright",
    startDate: "2021-03-09",
    employmentType: "Part Time",
    role: "Marketing",
    gender: "Male",
  },
  {
    employmentId: "1012",
    name: "Liam Scott",
    startDate: "2022-12-05",
    employmentType: "Full Time",
    role: "Operations",
    gender: "Male",
  },
  {
    employmentId: "1013",
    name: "Mia Taylor",
    startDate: "2021-10-20",
    employmentType: "Internship",
    role: "Finance",
    gender: "Female",
  },
  {
    employmentId: "1014",
    name: "Noah Young",
    startDate: "2023-05-30",
    employmentType: "Full Time",
    role: "Sales",
    gender: "Male",
  },
  {
    employmentId: "1015",
    name: "Olivia Martinez",
    startDate: "2020-08-12",
    employmentType: "Part Time",
    role: "Administration",
    gender: "Male",
  },
  {
    employmentId: "1016",
    name: "Paul Adams",
    startDate: "2023-07-07",
    employmentType: "Full Time",
    role: "IT & Security",
    gender: "Male",
  },
  {
    employmentId: "1006",
    name: "Frank White",
    startDate: "2022-09-14",
    employmentType: "Internship",
    role: "Operations",
    gender: "Male",
  },
  {
    employmentId: "1007",
    name: "Grace Hall",
    startDate: "2023-02-11",
    employmentType: "Part Time",
    role: "Administration",
    gender: "Female",
  },
  {
    employmentId: "1008",
    name: "Henry Lee",
    startDate: "2022-06-27",
    employmentType: "Full Time",
    role: "Sales",
    gender: "Male",
  },
  {
    employmentId: "1009",
    name: "Ivy King",
    startDate: "2023-08-02",
    employmentType: "Contract",
    role: "Human Resources",
    gender: "Female",
  },
  {
    employmentId: "1010",
    name: "Jack Green",
    startDate: "2023-04-18",
    employmentType: "Full Time",
    role: "IT & Security",
    gender: "Female",
  },
  {
    employmentId: "1011",
    name: "Kelly Wright",
    startDate: "2021-03-09",
    employmentType: "Part Time",
    role: "Marketing",
    gender: "Male",
  },
  {
    employmentId: "1012",
    name: "Liam Scott",
    startDate: "2022-12-05",
    employmentType: "Full Time",
    role: "Operations",
    gender: "Male",
  },
  {
    employmentId: "1013",
    name: "Mia Taylor",
    startDate: "2021-10-20",
    employmentType: "Internship",
    role: "Finance",
    gender: "Female",
  },
  {
    employmentId: "1014",
    name: "Noah Young",
    startDate: "2023-05-30",
    employmentType: "Full Time",
    role: "Sales",
    gender: "Male",
  },
  {
    employmentId: "1015",
    name: "Olivia Martinez",
    startDate: "2020-08-12",
    employmentType: "Part Time",
    role: "Administration",
    gender: "Male",
  },
  {
    employmentId: "1016",
    name: "Paul Adams",
    startDate: "2023-07-07",
    employmentType: "Full Time",
    role: "IT & Security",
    gender: "Male",
  },
  {
    employmentId: "1006",
    name: "Frank White",
    startDate: "2022-09-14",
    employmentType: "Internship",
    role: "Operations",
    gender: "Male",
  },
  {
    employmentId: "1007",
    name: "Grace Hall",
    startDate: "2023-02-11",
    employmentType: "Part Time",
    role: "Administration",
    gender: "Female",
  },
  {
    employmentId: "1008",
    name: "Henry Lee",
    startDate: "2022-06-27",
    employmentType: "Full Time",
    role: "Sales",
    gender: "Male",
  },
  {
    employmentId: "1009",
    name: "Ivy King",
    startDate: "2023-08-02",
    employmentType: "Contract",
    role: "Human Resources",
    gender: "Female",
  },
  {
    employmentId: "1010",
    name: "Jack Green",
    startDate: "2023-04-18",
    employmentType: "Full Time",
    role: "IT & Security",
    gender: "Female",
  },
  {
    employmentId: "1011",
    name: "Kelly Wright",
    startDate: "2021-03-09",
    employmentType: "Part Time",
    role: "Marketing",
    gender: "Male",
  },
  {
    employmentId: "1012",
    name: "Liam Scott",
    startDate: "2022-12-05",
    employmentType: "Full Time",
    role: "Operations",
    gender: "Male",
  },
  {
    employmentId: "1013",
    name: "Mia Taylor",
    startDate: "2021-10-20",
    employmentType: "Internship",
    role: "Finance",
    gender: "Female",
  },
  {
    employmentId: "1014",
    name: "Noah Young",
    startDate: "2023-05-30",
    employmentType: "Full Time",
    role: "Sales",
    gender: "Male",
  },
  {
    employmentId: "1015",
    name: "Olivia Martinez",
    startDate: "2020-08-12",
    employmentType: "Part Time",
    role: "Administration",
    gender: "Male",
  },
  {
    employmentId: "1016",
    name: "Paul Adams",
    startDate: "2023-07-07",
    employmentType: "Full Time",
    role: "IT & Security",
    gender: "Male",
  },
]
